language: go
go:
  - "1.12.x"

before_install:
  - make install

script:
  - make test.coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: true
